import moment from 'moment';
import AgGrid from '../../_components/aggrid';
import { Button } from 'flowbite-react';

const columnDefs = [
    {
        headerName: "Alumni ID",
        field: "alumniid",
        filter: false,
        sortable: false,
        resizable: false,
        suppressHeaderMenuButton: true,
        suppressMovable: true,
        enableRowGroup: false,
        suppressAutoSize: true,
        suppressSizeToFit: true,
        headerClass: 'cell-center',
        cellStyle: { textAlign: 'left' },
        width: "120vw",
        editable: false,
    },
    {
        headerName: "Full Name",
        valueGetter: (p) => {
            return `${p.data.firstname} ${p.data.lastname}`;
        },
        filter: false,
        sortable: false,
        resizable: false,
        suppressHeaderMenuButton: true,
        suppressMovable: true,
        enableRowGroup: false,
        suppressAutoSize: true,
        suppressSizeToFit: true,
        headerClass: 'cell-center',
        cellStyle: { textAlign: 'left' },
        width: "200vw",
        editable: false,
    },
    {
        headerName: "Birth Date",
        valueGetter: (p) => {
            return moment(p.data.birthdate).format("DD MMMM YYYY")
        },
        filter: false,
        sortable: false,
        resizable: false,
        suppressHeaderMenuButton: true,
        suppressMovable: true,
        enableRowGroup: false,
        suppressAutoSize: true,
        suppressSizeToFit: true,
        headerClass: 'cell-center',
        cellStyle: { textAlign: 'left' },
        width: "150vw",
        editable: false,
    },
    {
        headerName: "Last Year At BTB",
        field: "laststudentyear",
        filter: false,
        sortable: false,
        resizable: false,
        suppressHeaderMenuButton: true,
        suppressMovable: true,
        enableRowGroup: false,
        suppressAutoSize: true,
        suppressSizeToFit: true,
        headerClass: 'cell-center',
        cellStyle: { textAlign: 'left' },
        width: "150vw",
        editable: false,
    },
    {
        headerName: "Education",
        valueGetter: (p) => {
            return `${p.data?.edukasiOptions?.join(", ")}`;
        },
        filter: false,
        sortable: false,
        resizable: false,
        suppressHeaderMenuButton: true,
        suppressMovable: true,
        enableRowGroup: false,
        suppressAutoSize: true,
        suppressSizeToFit: true,
        headerClass: 'cell-center',
        cellStyle: { textAlign: 'left' },
        width: "300vw",
        editable: false,
    },
    {
        headerName: "Working Status",
        field: "statusKerjaOptions",
        filter: false,
        sortable: false,
        resizable: false,
        suppressHeaderMenuButton: true,
        suppressMovable: true,
        enableRowGroup: false,
        suppressAutoSize: true,
        suppressSizeToFit: true,
        headerClass: 'cell-center',
        cellStyle: { textAlign: 'left' },
        width: "150vw",
        editable: false,
    },
    {
        headerName: "Email",
        field: "email",
        cellRenderer: (p) =>  {
            return <Button onClick={() => window.location.href = "mailto:" + p?.data?.email} color={"warning"}>{p?.data?.email}</Button>;
        },
        filter: false,
        sortable: false,
        resizable: false,
        suppressHeaderMenuButton: true,
        suppressMovable: true,
        enableRowGroup: false,
        suppressAutoSize: true,
        suppressSizeToFit: true,
        headerClass: 'cell-center',
        cellStyle: { textAlign: 'left' },
        width: "200vw",
        editable: false,
    },
    {
        headerName: "Phone no",
        field: "phoneno",
        filter: false,
        sortable: false,
        resizable: false,
        suppressHeaderMenuButton: true,
        suppressMovable: true,
        enableRowGroup: false,
        suppressAutoSize: true,
        suppressSizeToFit: true,
        headerClass: 'cell-center',
        cellStyle: { textAlign: 'left' },
        width: "200vw",
        editable: false,
    },
    {
        headerName: "Photo",
        cellRenderer: (p) =>  {
            return <Button onClick={() => window.location.href = p?.data?.attachment[0]?.fileURL} color={"success"}>View</Button>;
        },
        filter: false,
        sortable: false,
        resizable: false,
        suppressHeaderMenuButton: true,
        suppressMovable: true,
        enableRowGroup: false,
        suppressAutoSize: true,
        suppressSizeToFit: true,
        headerClass: 'cell-center',
        cellStyle: { textAlign: 'left' },
        width: "100vw",
        editable: false,
    },
    {
        headerName: "Verify",
        cellRenderer: (p) =>  {
            return <Button color="info" onClick={() => window.location.href = '/admin/alumni/verify?id=' + p?.data?._id} className="mr-4">Verify</Button>
        },
        filter: false,
        sortable: false,
        resizable: false,
        suppressHeaderMenuButton: true,
        suppressMovable: true,
        enableRowGroup: false,
        suppressAutoSize: true,
        suppressSizeToFit: true,
        headerClass: 'cell-center',
        cellStyle: { textAlign: 'left' },
        width: "100vw",
        editable: false,
    },
];

const TableAlumniList = ({payload}) => {
    return  <AgGrid payload={payload} columnDefs={columnDefs} name="alumniListTable"/>
}

export default TableAlumniList;