name: automaticdeploy

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Automatic Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/aryanattapt/btbschool-fe
            git pull origin master
            docker stop btbschool-fe && docker system prune -af && docker compose up -d
            docker restart aryanattapt-nginx